# Generated by Django 2.2.7 on 2019-11-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
                ('img_cat', models.ImageField(default='category_default.jpg', upload_to='category')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='GraphicsCardCapacity',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='HardDiskCapacity',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='ProcessorFamily',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='RAMSize',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('inher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.Inher')),
            ],
            bases=('laptop.inher',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_lap', models.ImageField(default='laptop_default.jpg', upload_to='laptops')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.Color')),
                ('graphics_card_Capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.GraphicsCardCapacity')),
                ('hard_disk_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.HardDiskCapacity')),
                ('operating_System', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.OperatingSystem')),
                ('processor_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.ProcessorFamily')),
                ('ram_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.RAMSize')),
                ('screen_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.ScreenSize')),
            ],
        ),
    ]
